.build:apps:
  stage: build
  interruptible: true
  extends:
    - .dind_image
  script:
    - docker login -u friski12 -p $DOCKER_HUB_PASS
    - docker build -t friski12/go-helloworld:latest -f $CI_PROJECT_DIR/apps/go-app/Dockerfile ./$CI_PROJECT_DIR/apps/go-app

build:apps:dev:
  extends:
    - .build:apps
  rules:
    - !reference [.next-rules, on-apps-dev]
  variables:
    TAGGING: $CI_COMMIT_SHORT_SHA
  environment:
    name: 'dev'
    action: 'prepare'

