.build:apps:
  stage: build
  interruptible: true
  extends:
    - .dind_image
  script:
    - docker login -u friski12 -p $DOCKER_HUB_PASS

build:apps:dev:
  extends:
    - .build:apps
  rules:
    - !reference [.next-rules, on-apps-dev]
  variables:
    TAGGING: $CI_COMMIT_SHORT_SHA
  environment:
    name: 'dev'
    action: 'prepare'

