services:
  apps-go:
    image: 555730086661.dkr.ecr.ap-southeast-1.amazonaws.com/gcbc:$VERSION
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        # Change the host url here
        - 'traefik.http.routers.apps-go.rule=Host(`gcbc-staging.zero-one.cloud`)'
        - 'traefik.http.services.apps-go.loadbalancer.server.port=8080'
        - 'traefik.http.routers.apps-go.entrypoints=websecure'
        - 'traefik.http.routers.apps-go.tls=true'
        - 'traefik.http.routers.apps-go.tls.certresolver=leresolver'
    env_file:
      - ./.env
    networks:
      - swarm_network

networks:
  swarm_network:
    external: true
